import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import * as build from '../build/server'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
export const onRequest = createPagesFunctionHandler({ build })
  // if (ctx.env.ENVIRONMENT !== "development") {
  //   // eslint-disable-next-line import/no-unresolved
  // } else {
  //   const url = new URL(ctx.request.url)
  //   url.host = "localhost:3000"
  //   return fetch(url, {
  //     method: ctx.request.method,
  //     headers: ctx.request.headers,
  //     mode: ctx.request.mode,
  //     body: ctx.request.body,
  //     credentials: ctx.request.credentials,
  //     signal: ctx.request.signal,
  //     redirect: ctx.request.redirect,
  //   });
  // }
// }
