// Generated by Wrangler on Thu Mar 14 2024 14:45:41 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "development";
	D1: D1Database;
}
